import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Product renditions are pre-generated by scripts/optimize-images.mjs, so the runtime
  // image optimizer is not needed and the site can be exported statically if desired.
  images: { unoptimized: true },
  reactStrictMode: true,
};

export default nextConfig;
