// Turns assets/source/*.jpg into responsive WebP renditions under public/products/<id>/
// and writes src/data/assets.generated.ts with dimensions + blur placeholders.
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const SRC = "assets/source";
const OUT = "public/products";
const CARD_WIDTHS = [400, 600, 800]; // 4:5 renditions for grid cards
const LARGE = { w: 1024, h: 1280 }; // fit-inside rendition for gallery/zoom
const CARD_RATIO = 4 / 5;

// Optional per-asset trims (bottom fraction) parsed from assets.ts so the script has a single source of truth.
const assetsTs = fs.readFileSync("src/data/assets.ts", "utf8");
const trims = Object.fromEntries(
  [...assetsTs.matchAll(/id: "([0-9a-f]{8})"[^\n]*trimBottom: ([0-9.]+)/g)].map((m) => [m[1], Number(m[2])])
);

const files = fs.readdirSync(SRC).filter((f) => /\.jpe?g$/i.test(f)).sort();
const generated = {};

for (const file of files) {
  const id = file.slice(0, 8);
  const dir = path.join(OUT, id);
  fs.mkdirSync(dir, { recursive: true });

  let base = sharp(path.join(SRC, file)).rotate();
  const meta = await base.metadata();
  let { width, height } = meta;
  if (trims[id]) {
    const keep = Math.round(height * (1 - trims[id]));
    base = sharp(await base.extract({ left: 0, top: 0, width, height: keep }).toBuffer());
    height = keep;
  }
  const input = await base.toBuffer();
  const ratio = width / height;

  // Card rendition: cover-crop when the photo is already near 4:5; for very tall photos,
  // keep the full garment and fill the sides with a blurred, darkened copy instead of cropping.
  for (const w of CARD_WIDTHS) {
    const h = Math.round(w / CARD_RATIO);
    let img;
    if (ratio >= 0.7) {
      img = sharp(input).resize(w, h, { fit: "cover", position: "attention" });
    } else {
      const fg = await sharp(input).resize({ height: h, fit: "inside" }).toBuffer();
      const bg = await sharp(input)
        .resize(w, h, { fit: "cover" })
        .blur(30)
        .modulate({ brightness: 0.82, saturation: 0.9 })
        .toBuffer();
      img = sharp(bg).composite([{ input: fg, gravity: "centre" }]);
    }
    await img.webp({ quality: 78, effort: 5 }).toFile(path.join(dir, `card-${w}.webp`));
  }

  // Large rendition keeps the original aspect ratio (no crop) for the gallery.
  const large = await sharp(input)
    .resize(LARGE.w, LARGE.h, { fit: "inside", withoutEnlargement: true })
    .webp({ quality: 82, effort: 5 })
    .toFile(path.join(dir, "large.webp"));

  // Tiny blur placeholder (inline base64) for instant paint.
  const blur = await sharp(input).resize(16, 20, { fit: "cover" }).webp({ quality: 40 }).toBuffer();

  generated[id] = {
    width,
    height,
    large: { width: large.width, height: large.height },
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
  };
  process.stdout.write(`${id} ${width}x${height} -> cards ${CARD_WIDTHS.join("/")}, large ${large.width}x${large.height}\n`);
}

const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export interface GeneratedAsset {
  width: number;
  height: number;
  large: { width: number; height: number };
  blurDataURL: string;
}

export const GENERATED_ASSETS: Record<string, GeneratedAsset> = ${JSON.stringify(generated, null, 2)};
`;
fs.writeFileSync("src/data/assets.generated.ts", ts);
console.log(`\nwrote ${Object.keys(generated).length} assets to src/data/assets.generated.ts`);
