// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export interface GeneratedAsset {
  width: number;
  height: number;
  large: { width: number; height: number };
  blurDataURL: string;
}

export const GENERATED_ASSETS: Record<string, GeneratedAsset> = {
  "43781497": {
    "width": 539,
    "height": 970,
    "large": {
      "width": 539,
      "height": 970
    },
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JQBOmUABlPe9vyA0L0Z/eiiAA/qzlr7dhZQgFeSpVpU3xKMdK3LJ9Sse27MUOEcpktBELM7KrPTMcGQlKuNXBIUM1DoN1rHi3qHe5PNvMTP3mu6+9fcuLIN4LRIq44N3hkPO4zd8B8QrdKOZB6UHRAAA="
  },
  "57816702": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JQBOmUGP9pg9AH//ARU37e/+OO8IAAP5O6V0lPqw3sZta2hgo58Q1pwxw34GMlsEpYoBPaQXaQcwRnxpDIfOJmxDQkLB3ygDDTumW6FcBoB4pR/oB3nCp5QGfnAygk8/+h0+oGEHSnb4dKfz7+IaNoJRbgn5cecDRnmMzuslapU8AAAA="
  },
  "0380833b": {
    "width": 720,
    "height": 1280,
    "large": {
      "width": 720,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQAAJUqs39Q8xlQQA/LOhgXotzBlo38VZfBul6Bipu78VpAz0Bd+A2NAz3irIHv0pf73LRSK/VpNHlMss7Cf3nojNmRUfXRoC4+qI5C0QrfankSA3vBnPLEwAAA=="
  },
  "03ed0b9a": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JQBOmUGP9pg9AH//ARU37e/+OO8IAAP5O6V0lPqw3sZta2hgo58Q1pwxw34GMlsEpYoBPaQXaQcwRnxpDIfOJmxDQkLB3ygDDTumW6FcBoB4pR/oB3nCp5QGfnAygk8/+h0+oGEHSnb4dKfz7+IaNoJRbgn5cecDRnmMzuslapU8AAAA="
  },
  "14f66cdb": {
    "width": 589,
    "height": 1280,
    "large": {
      "width": 589,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JQBOmUBDABIXXwtnIyjUyLnEgC5bgAP7uhIpUZy7Gq6TFeOfXHThas5wSwZTsm/F3ftlPrzfap1LCzIQHFTX2K4GKh1kDKBgHAei3teooJg9279BmMqlX2ZbwAA=="
  },
  "1c7c42b6": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZgCw7BxvNY/DTDrwyf4AAP7ToHKi0XFMpinaX10cLC10TdKZvs2a4MYs8252/4TN0ST87hnFXs9LwfRwlCk8ag/Q8TnW7Hj3jXsMJgnXViW337KsoorkmD/jf7E+OuUX8dXlmn5/NQXPIU1lMtghwWqIAA=="
  },
  "21baac63": {
    "width": 688,
    "height": 1280,
    "large": {
      "width": 688,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBYdgyMpypoHbfThMogA/tOkP6BN6vMKn15Xq7XS2TnJs1/ZlWk8CxY4eQhs2I6cy2p5s5dp27EYnkipJjeg1sKTn4/NJxNPOMyFfY8NrS46gIMyfydZYZgAAA=="
  },
  "227ab51e": {
    "width": 720,
    "height": 1280,
    "large": {
      "width": 720,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYwC7AdwA2SmysxEHaFUNdAgAANtglsX74ULm87f2qrOYi0uIwYtHwaB6HAyi3M/M/7snYAhm7gvPnERk8gDlJY2ClIa2TvS4joggZoVrv+OGXGatue30vb4Xhki0wpLcwAAA"
  },
  "2a1d6ecf": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYgCsLwABe3bg45sFaPKKAAD6O9+poF+c41QKsAlbKzTFTxQ5dUlhjsAagsSqE0CWonfKKM1Me3SYGygyghPqMKWJAyXwpnASrEF5lv2YIF0ftVDjszQ6QPoI6Q4fhSSf+Gi6jBPZn6RttOUDov4amPvkXAAA"
  },
  "2bbb2b80": {
    "width": 806,
    "height": 1280,
    "large": {
      "width": 806,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JagCdACHc64Z8SCBM4xLvUAD331S8WKT6mmR1kytXwWyX+f/zY73XP11EsPyr28AgLuQEDcWAEpLwE8Nx224DY+L/DkPmyskCNvlcl9dZizhMrxvzw8oP5Y2Ks3aKxdBEmTqUKt3HtcZ54NAR2n0Tkyow56Dj7yEVAAAA"
  },
  "2f2b0e18": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBWAA0N6ulRndnfMcAD+5EbG+w3v3DNuS1uyB68uYP+UCuv9+28/OFyeSyPP99RRSmOpstxilJIn/N/BfL5R8RaJqXNbOCqluTKriAA="
  },
  "32b1efeb": {
    "width": 540,
    "height": 1092,
    "large": {
      "width": 540,
      "height": 1092
    },
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JZACdMoADaYV+MnaCv7k7Qn7UQAD+wmbWrmN/UAq4bNqoatSsEtQPXdApTPCs90jdfngN3SxuM87LJ+e/gkFGW6No2nMK6iMMeLGqgQxgucPJbNxFGF4wfhE3L36R57LwTqmLdhVFlURA3L7HaFa5m7AGPAAA"
  },
  "334ff912": {
    "width": 720,
    "height": 1280,
    "large": {
      "width": 720,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYwC7AdwA2SmysxEHaFUNdAgAANtglsX74ULm87f2qrOYi0uIwYtHwaB6HAyi3M/M/7snYAhm7gvPnERk8gDlJY2ClIa2TvS4joggZoVrv+OGXGatue30vb4Xhki0wpLcwAAA"
  },
  "3563edfd": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBWAA0N6ulRndnfMcAD+5EbG+w3v3DNuS1uyB68uYP+UCuv9+28/OFyeSyPP99RRSmOpstxilJIn/N/BfL5R8RaJqXNbOCqluTKriAA="
  },
  "489c01b6": {
    "width": 720,
    "height": 1280,
    "large": {
      "width": 720,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZACdMoACw47gONQHXfYgAP7o/JTrK31Ph4TB8acXcNtfebLJrsrBJj/5lixPerdY+6CEb/V4plkn+T95f1c6Q674imRlqzuw2L1gUUk0rMYW5VLncl5E7o9E6KPVzGR8xAAA"
  },
  "4a684780": {
    "width": 589,
    "height": 1280,
    "large": {
      "width": 589,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBOgA/B78GJzTz6JqV0AAP7Nl0nHeukPH3uzUc54to9ovP1E/O1NG5PzSBQqOS4OkGFGRR4Ii4oQrrQAAA=="
  },
  "50cadec0": {
    "width": 589,
    "height": 1280,
    "large": {
      "width": 589,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JYwCdABGrzTFq2DgYAP5L+7DcXl9isnzCjQgpGqCU76euJMdUAD06CYFuTZDZy5p5y9zY47H/YEiG1HF6k5sJ1LAAAA=="
  },
  "5451df09": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBWAtQAl+iQ0qWr/lnAA/KudMUsw4ZcL++zcYk7dha+tmQG2aENHevLiQ6vPg0macZ88cYtSXS5DZV6u/r6lJaB4ZNLGXCjgI6kH6A3vFfDCoIavlgQr6AA="
  },
  "6647c33a": {
    "width": 688,
    "height": 1280,
    "large": {
      "width": 688,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBYdgyMpypoHbfThMogA/tOkP6BN6vMKn15Xq7XS2TnJs1/ZlWk8CxY4eQhs2I6cy2p5s5dp27EYnkipJjeg1sKTn4/NJxNPOMyFfY8NrS46gIMyfydZYZgAAA=="
  },
  "6c17dfaf": {
    "width": 589,
    "height": 1280,
    "large": {
      "width": 589,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JYwCdABGrzTFq2DgYAP5L+7DcXl9isnzCjQgpGqCU76euJMdUAD06CYFuTZDZy5p5y9zY47H/YEiG1HF6k5sJ1LAAAA=="
  },
  "6cad7095": {
    "width": 720,
    "height": 1280,
    "large": {
      "width": 720,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JZACdMoR3AkgBB20bPFGRD10AAP7Bz7WDDaI/mGdnm0PSshn9q1+Eow+imSpPHm0R7sXjh1MLxcnZLcJMK7cw9HyWFPKFWgBKfgr2TILQzaxTppL5TxFGlCD3j7ur3GK/96wIcMjtZcaGgu4/SToeUEj+AA=="
  },
  "7009df62": {
    "width": 720,
    "height": 1280,
    "large": {
      "width": 720,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JZACdMoR3AkgBB20bPFGRD10AAP7Bz7WDDaI/mGdnm0PSshn9q1+Eow+imSpPHm0R7sXjh1MLxcnZLcJMK7cw9HyWFPKFWgBKfgr2TILQzaxTppL5TxFGlCD3j7ur3GK/96wIcMjtZcaGgu4/SToeUEj+AA=="
  },
  "7b607a63": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JbACdMoACazgiCS24tJypEAD+tnRXMucBzV01sLzi+5Mea6XX0sND/bOr6c41X4E3EghJeljbmmxcABtaKDfxqdRQ1C157xJqZZhTUVuACP5RT7EDayTb1UCgayJmjSLEgAAA"
  },
  "7b6a84c8": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYgCsLwABe3bg45sFaPKKAAD6O9+poF+c41QKsAlbKzTFTxQ5dUlhjsAagsSqE0CWonfKKM1Me3SYGygyghPqMKWJAyXwpnASrEF5lv2YIF0ftVDjszQ6QPoI6Q4fhSSf+Gi6jBPZn6RttOUDov4amPvkXAAA"
  },
  "878f984e": {
    "width": 720,
    "height": 1280,
    "large": {
      "width": 720,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZACdMoACw47gONQHXfYgAP7o/JTrK31Ph4TB8acXcNtfebLJrsrBJj/5lixPerdY+6CEb/V4plkn+T95f1c6Q674imRlqzuw2L1gUUk0rMYW5VLncl5E7o9E6KPVzGR8xAAA"
  },
  "8bdf63fd": {
    "width": 720,
    "height": 1280,
    "large": {
      "width": 720,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBhQATX8A1dRZgAA94J/Vq/sELMoCgQqRqQ7x1fLsuqol+UC8lnBJAiKYxpDUFua3e6ji2pz1qbQRnWXy3Q95OWIXsIqm0rEL2EVT5RSB3u8ZH8AAA=="
  },
  "96024be0": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBWAtQAl+iQ0qWr/lnAA/KudMUsw4ZcL++zcYk7dha+tmQG2aENHevLiQ6vPg0macZ88cYtSXS5DZV6u/r6lJaB4ZNLGXCjgI6kH6A3vFfDCoIavlgQr6AA="
  },
  "99d515ce": {
    "width": 720,
    "height": 1280,
    "large": {
      "width": 720,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JYgC7ABn3D0b7DIpvgAAA99vYCCHcfjIYIz/lOr0oNTrhgMIyk5Ddw4tIYW3V8vrFYjaCRgIc18KZ2mC70S16adBDJ6QAAAA="
  },
  "a841c54e": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JbACdMoLUABAq1IQ2Bn8mWMQA/t43wmTzk41zC9QC3xOFBCWA1OGWLtIY0bDQ3fKb3WFq1pBVNvr++zyc5klo9vCn4HO01VZ4K3MAJRVetp1fasqDBUqQT5pqbB7HPlnjyEq4kSSmpWi8JVB75kh4PS/U5Vgj19r3J/nL8e9GauMqx39lX19/AAA="
  },
  "b1cb4c44": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZgCw7BxvNY/DTDrwyf4AAP7ToHKi0XFMpinaX10cLC10TdKZvs2a4MYs8252/4TN0ST87hnFXs9LwfRwlCk8ag/Q8TnW7Hj3jXsMJgnXViW337KsoorkmD/jf7E+OuUX8dXlmn5/NQXPIU1lMtghwWqIAA=="
  },
  "c10fe6e1": {
    "width": 720,
    "height": 1280,
    "large": {
      "width": 720,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQAAJUqs39Q8xlQQA/LOhgXotzBlo38VZfBul6Bipu78VpAz0Bd+A2NAz3irIHv0pf73LRSK/VpNHlMss7Cf3nojNmRUfXRoC4+qI5C0QrfankSA3vBnPLEwAAA=="
  },
  "d0995380": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JagCdIDdxAAPrni0tVtqeniAA/ccIZOoZ3hqFd3UhWz/uHUNMnGvegKNDDe+i2jnpdjJvhIPy9yWmPvC0kA6nULPIjllc4QP8mVa0Q4EYQZvKqP40Sxu2TyTM4oBvO4A8OGJr0h5xx35RGZkB5pQPwAl5z7kdfd9cq7VdVlGblLgA"
  },
  "d0f83124": {
    "width": 589,
    "height": 1280,
    "large": {
      "width": 589,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JQBOmUBDABIXXwtnIyjUyLnEgC5bgAP7uhIpUZy7Gq6TFeOfXHThas5wSwZTsm/F3ftlPrzfap1LCzIQHFTX2K4GKh1kDKBgHAei3teooJg9279BmMqlX2ZbwAA=="
  },
  "f07534b1": {
    "width": 589,
    "height": 1280,
    "large": {
      "width": 589,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBOgA/B78GJzTz6JqV0AAP7Nl0nHeukPH3uzUc54to9ovP1E/O1NG5PzSBQqOS4OkGFGRR4Ii4oQrrQAAA=="
  },
  "f2270765": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JbACdMoACazgiCS24tJypEAD+tnRXMucBzV01sLzi+5Mea6XX0sND/bOr6c41X4E3EghJeljbmmxcABtaKDfxqdRQ1C157xJqZZhTUVuACP5RT7EDayTb1UCgayJmjSLEgAAA"
  },
  "f55472d6": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JbACdMoLUABAq1IQ2Bn8mWMQA/t43wmTzk41zC9QC3xOFBCWA1OGWLtIY0bDQ3fKb3WFq1pBVNvr++zyc5klo9vCn4HO01VZ4K3MAJRVetp1fasqDBUqQT5pqbB7HPlnjyEq4kSSmpWi8JVB75kh4PS/U5Vgj19r3J/nL8e9GauMqx39lX19/AAA="
  },
  "fac8c992": {
    "width": 960,
    "height": 1280,
    "large": {
      "width": 960,
      "height": 1280
    },
    "blurDataURL": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JagCdIDdxAAPrni0tVtqeniAA/ccIZOoZ3hqFd3UhWz/uHUNMnGvegKNDDe+i2jnpdjJvhIPy9yWmPvC0kA6nULPIjllc4QP8mVa0Q4EYQZvKqP40Sxu2TyTM4oBvO4A8OGJr0h5xx35RGZkB5pQPwAl5z7kdfd9cq7VdVlGblLgA"
  }
};
